ci:
  autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        # Prevent giant files from being committed.
      - id: check-ast
        # Simply check whether files parse as valid python.
      - id: check-case-conflict
        # Check for files with names that would conflict on a case-insensitive
        # filesystem like MacOS HFS+ or Windows FAT.
      - id: check-json
        # Attempts to load all json files to verify syntax.
      - id: check-merge-conflict
        # Check for files that contain merge conflict strings.
      - id: check-symlinks
        # Checks for symlinks which do not point to anything.
      - id: check-toml
        # Attempts to load all TOML files to verify syntax.
      - id: check-xml
        # Attempts to load all xml files to verify syntax.
      - id: check-yaml
        # Attempts to load all yaml files to verify syntax.
      - id: debug-statements
        # Check for debugger imports and py37+ breakpoint() calls in python
        # source.
      - id: detect-private-key
        # Checks for the existence of private keys.
      - id: end-of-file-fixer
        # Makes sure files end in a newline and only a newline.
        exclude: ".*(svg.*|extern.*|_templates.*)$"
      - id: trailing-whitespace
        # Trims trailing whitespace.
        exclude: ".*(data.*|extern.*)$"

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-mock-methods
        # Prevent common mistakes of assert mck.not_called(), assert
        # mck.called_once_with(...) and mck.assert_called.
      - id: rst-directive-colons
        # Detect mistake of rst directive not ending with double colon.
      - id: rst-inline-touching-normal
        # Detect mistake of inline code touching normal text in rst.
      - id: text-unicode-replacement-char
        # Forbid files which have a UTF-8 Unicode replacement character.
      - id: python-check-blanket-noqa
        # Enforce that all noqa annotations always occur with specific codes.

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.11.0
    hooks:
      - id: pyupgrade
        args: ["--py39-plus"]
        exclude: ".*(extern.*)$"

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        additional_dependencies: [toml]
      - id: isort
        name: isort (cython)
        types: [cython]
        additional_dependencies: [toml]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--ignore", "E501,W503"]

  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa

  # - repo: https://github.com/MarcoGorelli/absolufy-imports
  #   rev: v0.3.1
  #   hooks:
  #   - id: absolufy-imports
